version: '3.8'

services:
  react:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./react
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
        - USER_NAME=${USER_NAME}
        - NODEJS_MAJOR_VERSION=${NODEJS_MAJOR_VERSION}
    volumes:
      - home:/home
    user: ${USER_NAME}
    stdin_open: true
    tty: true

volumes:
  home:
    name: ${VOLUME_NAME}

networks:
  default:
    name: ${NETWORK_NAME}
